version: '3'
services:
  postgreSQL:
    container_name: postgreSqlContainer
    image: postgres:13.1
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'